on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
    #PIC18F4550
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F4550
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/88cefda1241159b0b1d8db173912a5b8
          gist_title: Pr치ctica-18 HCSR04 4550-MikroC.c
          gist_description: Pr치cticas MikroC Pro for PIC
          github_file: Proyecto/4550/HCSR04.c
          file_encoding: WINDOWS-1252
    #PIC18F45K50
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F45K50
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/547f2063d31a52df1c316cabde459109
          gist_title: Pr치ctica-18 HCSR04 45K50-MikroC.c
          gist_description: Pr치cticas MikroC Pro for PIC
          github_file: Proyecto/45K50/HCSR04.c
          file_encoding: WINDOWS-1252